<x-layout>
    <x-navbarDark />

  <div class="container">
    <div class="row justify-content-start m-5">
        <h3 class="border-bottom border-dark"> Video Maker</h3>
        <div class="col-12  d-flex">
            <img src="/media/videomaker.jpg" alt="" class="imgOrizontal m-5">
            
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis saepe repellendus aut, dolor molestias delectus perferendis ipsum excepturi, nulla vel eum accusantium optio, alias reprehenderit a placeat reiciendis modi esse? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum corrupti unde praesentium. Sequi est perspiciatis, necessitatibus et laborum veniam a reprehenderit nisi amet voluptas ullam repudiandae voluptates eius neque at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem accusantium beatae. Doloribus cum sint quisquam tenetur repudiandae? Nulla repudiandae aliquid optio consequuntur tenetur quae ab possimus animi reprehenderit autem! Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, ad alias laboriosam harum unde aliquam fugiat natus rem sapiente tempore cum beatae id dolores totam dolorem libero. Nesciunt, quasi Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos libero dolorem reprehenderit fuga dignissimos. Tempore earum quaerat sint velit quas perspiciatis mollitia, error magnam, accusamus quasi iusto est odit quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio atque at facilis modi! Deleniti ea pariatur nihil laudantium aliquid, similique ut quas itaque ipsum nisi accusantium, architecto aperiam asperiores quia!</p>
        </div>
    </div>
    <div class="row justify-content-end align-items-end">
        <h3 class="border-bottom border-dark text-end"> Fotografo </h3>
        <div class="col-12  d-flex ">
            
            <p class="m-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis saepe repellendus aut, dolor molestias delectus perferendis ipsum excepturi, nulla vel eum accusantium optio, alias reprehenderit a placeat reiciendis modi esse? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum corrupti unde praesentium. Sequi est perspiciatis, necessitatibus et laborum veniam a reprehenderit nisi amet voluptas ullam repudiandae voluptates eius neque at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem accusantium beatae. Doloribus cum sint quisquam tenetur repudiandae? Nulla repudiandae aliquid optio consequuntur tenetur quae ab possimus animi reprehenderit autem! Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, ad alias laboriosam harum unde aliquam fugiat natus rem sapiente tempore cum beatae id dolores totam dolorem libero. Nesciunt, quasi Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos libero dolorem reprehenderit fuga dignissimos. Tempore earum quaerat sint velit quas perspiciatis mollitia, error magnam, accusamus quasi iusto est odit quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio atque at facilis modi! Deleniti ea pariatur nihil laudantium aliquid, similique ut quas itaque ipsum nisi accusantium, architecto aperiam asperiores quia! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Totam voluptatum enim exercitationem inventore, beatae facere eligendi perspiciatis blanditiis neque rem a accusantium placeat eaque reiciendis laboriosam in voluptas at sed. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum rerum nisi iusto, velit nam similique quisquam modi eaque dignissimos explicabo repudiandae molestias aut veniam maiores quae debitis sapiente eligendi excepturi? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magni nemo, nostrum, accusamus laborum quas error praesentium eius mollitia nulla quasi maiores necessitatibus fuga molestias vitae accusantium id, ipsum cum deserunt!</p>
            <img src="/media/fotografo.jpg" alt="" class="imgVertical ">
        </div>
    </div>
    <div class="row justify-content-start m-5">
        <h3 class="border-bottom border-dark"> Passione </h3>
        <div class="col-12  d-flex">
            <img src="/media/passione.jpg" alt="" class="imgOrizontal m-5">
            
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis saepe repellendus aut, dolor molestias delectus perferendis ipsum excepturi, nulla vel eum accusantium optio, alias reprehenderit a placeat reiciendis modi esse? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum corrupti unde praesentium. Sequi est perspiciatis, necessitatibus et laborum veniam a reprehenderit nisi amet voluptas ullam repudiandae voluptates eius neque at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem accusantium beatae. Doloribus cum sint quisquam tenetur repudiandae? Nulla repudiandae aliquid optio consequuntur tenetur quae ab possimus animi reprehenderit autem! Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, ad alias laboriosam harum unde aliquam fugiat natus rem sapiente tempore cum beatae id dolores totam dolorem libero. Nesciunt, quasi Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos libero dolorem reprehenderit fuga dignissimos. Tempore earum quaerat sint velit quas perspiciatis mollitia, error magnam, accusamus quasi iusto est odit quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio atque at facilis modi! Deleniti ea pariatur nihil laudantium aliquid, similique ut quas itaque ipsum nisi accusantium, architecto aperiam asperiores quia!</p>
        </div>
    </div>
    <div class="row justify-content-end align-items-end">
        <h3 class="border-bottom border-dark text-end"> Dedizione </h3>
        <div class="col-12  d-flex ">
            
            <p class="m-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis saepe repellendus aut, dolor molestias delectus perferendis ipsum excepturi, nulla vel eum accusantium optio, alias reprehenderit a placeat reiciendis modi esse? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum corrupti unde praesentium. Sequi est perspiciatis, necessitatibus et laborum veniam a reprehenderit nisi amet voluptas ullam repudiandae voluptates eius neque at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem accusantium beatae. Doloribus cum sint quisquam tenetur repudiandae? Nulla repudiandae aliquid optio consequuntur tenetur quae ab possimus animi reprehenderit autem! Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, ad alias laboriosam harum unde aliquam fugiat natus rem sapiente tempore cum beatae id dolores totam dolorem libero. Nesciunt, quasi Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos libero dolorem reprehenderit fuga dignissimos. Tempore earum quaerat sint velit quas perspiciatis mollitia, error magnam, accusamus quasi iusto est odit quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio atque at facilis modi! Deleniti ea pariatur nihil laudantium aliquid, similique ut quas itaque ipsum nisi accusantium, architecto aperiam asperiores quia! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Totam voluptatum enim exercitationem inventore, beatae facere eligendi perspiciatis blanditiis neque rem a accusantium placeat eaque reiciendis laboriosam in voluptas at sed. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum rerum nisi iusto, velit nam similique quisquam modi eaque dignissimos explicabo repudiandae molestias aut veniam maiores quae debitis sapiente eligendi excepturi? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magni nemo, nostrum, accusamus laborum quas error praesentium eius mollitia nulla quasi maiores necessitatibus fuga molestias vitae accusantium id, ipsum cum deserunt!</p>
            <img src="/media/dedizione.jpg" alt="" class="imgVertical ">
        </div>
    </div>
  </div>
 

</x-layout>